### ISSUE TITLE
Need a simple email client stub 

### ISSUE THREAD

**Issue by BilalAM** [iAM9/Utilities#3]
Add a simple email client class as we discussed . 
Should have ability to enter id and password along with message body . 
@iAM9  please look into the link i sent you earlier .

**Comment by iAM9** [comment]
Added first commit.
Keep in mind that this is still WIP
[https://github.com/iAM9/Utilities/commit/0f0578dee6736e4b95c0d4a37b2eacefba5ef66e](url)

**Comment by BilalAM** [comment]
Closing under : 0f0578dee6736e4b95c0d4a37b2eacefba5ef66e
